services:
  tornado:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_app.celery worker --beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
